<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        DB::table("centers")->insert([
            [
                "id" => 1,
                "name" => "Centre Sant Pere Vallparadís",
                "email" => "santpere@vallparadis.org",
                "address" => "Carrer de Sant Pere, 12, Terrassa",
                "phone" => "937001001",
                "created_at" => now()->subDays(30),
                "updated_at" => now()->subDays(29),
            ],
            [
                "id" => 2,
                "name" => "Centre Can Palet",
                "email" => "canpalet@vallparadis.org",
                "address" => "Carrer del Castell, 45, Terrassa",
                "phone" => "937002002",
                "created_at" => now()->subDays(27),
                "updated_at" => now()->subDays(26),
            ],
            [
                "id" => 3,
                "name" => "Vallparadís Ca n'Anglada",
                "email" => "cnanglada@vallparadis.org",
                "address" => "Plaça d'Europa, 3, Terrassa",
                "phone" => "937003003",
                "created_at" => now()->subDays(24),
                "updated_at" => now()->subDays(23),
            ],
            [
                "id" => 4,
                "name" => "Centre Les Fonts",
                "email" => "lesfonts@vallparadis.org",
                "address" => "Carrer de les Fonts, 7, Terrassa",
                "phone" => "937004004",
                "created_at" => now()->subDays(21),
                "updated_at" => now()->subDays(20),
            ],
            [
                "id" => 5,
                "name" => "Sant Llorenç Vallparadís",
                "email" => "santllorenc@vallparadis.org",
                "address" => "Avinguda del Vallès, 88, Terrassa",
                "phone" => "937005005",
                "created_at" => now()->subDays(18),
                "updated_at" => now()->subDays(17),
            ],
            [
                "id" => 6,
                "name" => "Centre Can Roca",
                "email" => "canroca@vallparadis.org",
                "address" => "Carrer de Can Roca, 21, Terrassa",
                "phone" => "937006006",
                "created_at" => now()->subDays(15),
                "updated_at" => now()->subDays(14),
            ],
            [
                "id" => 7,
                "name" => "Ca l'Estruch",
                "email" => "cale_struch@vallparadis.org",
                "address" => "Carrer de l'Estruch, 5, Terrassa",
                "phone" => "937007007",
                "created_at" => now()->subDays(12),
                "updated_at" => now()->subDays(11),
            ],
            [
                "id" => 8,
                "name" => "Vallparadís Torrebonica",
                "email" => "torrebonica@vallparadis.org",
                "address" => "Passeig de la Torrebonica, 2, Terrassa",
                "phone" => "937008008",
                "created_at" => now()->subDays(9),
                "updated_at" => now()->subDays(8),
            ],
            [
                "id" => 9,
                "name" => "Centre Can Rull",
                "email" => "canrull@vallparadis.org",
                "address" => "Carrer del Rull, 14, Terrassa",
                "phone" => "937009009",
                "created_at" => now()->subDays(6),
                "updated_at" => now()->subDays(5),
            ],
            [
                "id" => 10,
                "name" => "Vallparadís Les Arenes",
                "email" => "lesarenes@vallparadis.org",
                "address" => "Carrer de les Arenes, 9, Terrassa",
                "phone" => "937010010",
                "created_at" => now()->subDays(3),
                "updated_at" => now()->subDays(2),
            ],
            [
                "id" => 11,
                "name" => "Centre Sant Quirze",
                "email" => "santquirze@vallparadis.org",
                "address" => "Carrer de Sant Quirze, 10, Terrassa",
                "phone" => "937011011",
                "created_at" => now()->subDays(32),
                "updated_at" => now()->subDays(31),
            ],
            [
                "id" => 12,
                "name" => "Vallparadís Can Anglada",
                "email" => "cananglada@vallparadis.org",
                "address" => "Carrer de Can Anglada, 7, Terrassa",
                "phone" => "937012012",
                "created_at" => now()->subDays(31),
                "updated_at" => now()->subDays(30),
            ],
            [
                "id" => 13,
                "name" => "Centre La Maurina",
                "email" => "lamaurina@vallparadis.org",
                "address" => "Carrer de la Maurina, 3, Terrassa",
                "phone" => "937013013",
                "created_at" => now()->subDays(30),
                "updated_at" => now()->subDays(29),
            ],
            [
                "id" => 14,
                "name" => "Vallparadís Sant Llorenç",
                "email" => "santllorenc2@vallparadis.org",
                "address" => "Avinguda del Vallès, 50, Terrassa",
                "phone" => "937014014",
                "created_at" => now()->subDays(28),
                "updated_at" => now()->subDays(27),
            ],
            [
                "id" => 15,
                "name" => "Centre Can Rull",
                "email" => "canrull2@vallparadis.org",
                "address" => "Carrer del Rull, 20, Terrassa",
                "phone" => "937015015",
                "created_at" => now()->subDays(27),
                "updated_at" => now()->subDays(26),
            ],
            [
                "id" => 16,
                "name" => "Vallparadís Torre del Palau",
                "email" => "torredelpalau@vallparadis.org",
                "address" => "Passeig del Palau, 8, Terrassa",
                "phone" => "937016016",
                "created_at" => now()->subDays(26),
                "updated_at" => now()->subDays(25),
            ],
            [
                "id" => 17,
                "name" => "Centre Ca n'Aurell",
                "email" => "canaurell@vallparadis.org",
                "address" => "Carrer de Ca n'Aurell, 15, Terrassa",
                "phone" => "937017017",
                "created_at" => now()->subDays(25),
                "updated_at" => now()->subDays(24),
            ],
            [
                "id" => 18,
                "name" => "Vallparadís Les Arenes",
                "email" => "lesarenes2@vallparadis.org",
                "address" => "Carrer de les Arenes, 12, Terrassa",
                "phone" => "937018018",
                "created_at" => now()->subDays(24),
                "updated_at" => now()->subDays(23),
            ],
            [
                "id" => 19,
                "name" => "Centre La Gripia",
                "email" => "lagripia@vallparadis.org",
                "address" => "Carrer de la Gripia, 4, Terrassa",
                "phone" => "937019019",
                "created_at" => now()->subDays(23),
                "updated_at" => now()->subDays(22),
            ],
            [
                "id" => 20,
                "name" => "Vallparadís Can Palet Nord",
                "email" => "canpaletnord@vallparadis.org",
                "address" => "Carrer del Nord, 6, Terrassa",
                "phone" => "937020020",
                "created_at" => now()->subDays(22),
                "updated_at" => now()->subDays(21),
            ],
            [
                "id" => 21,
                "name" => "Centre Can Boada",
                "email" => "canboada@vallparadis.org",
                "address" => "Carrer de Can Boada, 2, Terrassa",
                "phone" => "937021021",
                "created_at" => now()->subDays(21),
                "updated_at" => now()->subDays(20),
            ],
            [
                "id" => 22,
                "name" => "Vallparadís Sant Jaume",
                "email" => "santjaume@vallparadis.org",
                "address" => "Carrer de Sant Jaume, 9, Terrassa",
                "phone" => "937022022",
                "created_at" => now()->subDays(20),
                "updated_at" => now()->subDays(19),
            ],
            [
                "id" => 23,
                "name" => "Centre Les Arenes Sud",
                "email" => "lesarenessud@vallparadis.org",
                "address" => "Carrer de les Arenes, 18, Terrassa",
                "phone" => "937023023",
                "created_at" => now()->subDays(19),
                "updated_at" => now()->subDays(18),
            ],
            [
                "id" => 24,
                "name" => "Vallparadís Can Roca Nord",
                "email" => "canrocanord@vallparadis.org",
                "address" => "Carrer de Can Roca, 30, Terrassa",
                "phone" => "937024024",
                "created_at" => now()->subDays(18),
                "updated_at" => now()->subDays(17),
            ],
            [
                "id" => 25,
                "name" => "Centre Sant Llorenç Sud",
                "email" => "santllorencsud@vallparadis.org",
                "address" => "Avinguda del Vallès, 100, Terrassa",
                "phone" => "937025025",
                "created_at" => now()->subDays(17),
                "updated_at" => now()->subDays(16),
            ],
            [
                "id" => 26,
                "name" => "Vallparadís La Maurina",
                "email" => "lamaurina2@vallparadis.org",
                "address" => "Carrer de la Maurina, 8, Terrassa",
                "phone" => "937026026",
                "created_at" => now()->subDays(16),
                "updated_at" => now()->subDays(15),
            ],
            [
                "id" => 27,
                "name" => "Centre Can Rull Nord",
                "email" => "canrullnord@vallparadis.org",
                "address" => "Carrer del Rull, 25, Terrassa",
                "phone" => "937027027",
                "created_at" => now()->subDays(15),
                "updated_at" => now()->subDays(14),
            ],
            [
                "id" => 28,
                "name" => "Vallparadís Sant Pere Nord",
                "email" => "santperenord@vallparadis.org",
                "address" => "Carrer de Sant Pere, 20, Terrassa",
                "phone" => "937028028",
                "created_at" => now()->subDays(14),
                "updated_at" => now()->subDays(13),
            ],
            [
                "id" => 29,
                "name" => "Centre Torrebonica Sud",
                "email" => "torrebonicasud@vallparadis.org",
                "address" => "Passeig de la Torrebonica, 12, Terrassa",
                "phone" => "937029029",
                "created_at" => now()->subDays(13),
                "updated_at" => now()->subDays(12),
            ],
            [
                "id" => 30,
                "name" => "Vallparadís Can Anglada Sud",
                "email" => "canangladasud@vallparadis.org",
                "address" => "Carrer de Can Anglada, 14, Terrassa",
                "phone" => "937030030",
                "created_at" => now()->subDays(12),
                "updated_at" => now()->subDays(11),
            ]
            ]
        );
    }
}
