<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CourseUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("course_users")->insert([
            [
                "id" => 1,
                "user_id" => 1,
                "course_id" => 1,
                "certificate" => "LLIURAT",
                "created_at" => now()->subDays(30),
                "updated_at" => now()->subDays(25),
            ],
            [
                "id" => 2,
                "user_id" => 10,
                "course_id" => 1,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(29),
                "updated_at" => now()->subDays(24),
            ],
            [
                "id" => 3,
                "user_id" => 15,
                "course_id" => 1,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(28),
                "updated_at" => now()->subDays(23),
            ],
            [
                "id" => 4,
                "user_id" => 2,
                "course_id" => 2,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(27),
                "updated_at" => now()->subDays(22),
            ],
            [
                "id" => 5,
                "user_id" => 6,
                "course_id" => 2,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(26),
                "updated_at" => now()->subDays(21),
            ],
            [
                "id" => 6,
                "user_id" => 11,
                "course_id" => 2,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(25),
                "updated_at" => now()->subDays(20),
            ],
            [
                "id" => 7,
                "user_id" => 3,
                "course_id" => 3,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(24),
                "updated_at" => now()->subDays(19),
            ],
            [
                "id" => 8,
                "user_id" => 7,
                "course_id" => 3,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(23),
                "updated_at" => now()->subDays(18),
            ],
            [
                "id" => 9,
                "user_id" => 12,
                "course_id" => 3,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(22),
                "updated_at" => now()->subDays(17),
            ],
            [
                "id" => 10,
                "user_id" => 4,
                "course_id" => 4,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(21),
                "updated_at" => now()->subDays(16),
            ],
            [
                "id" => 11,
                "user_id" => 8,
                "course_id" => 4,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(20),
                "updated_at" => now()->subDays(15),
            ],
            [
                "id" => 12,
                "user_id" => 13,
                "course_id" => 4,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(19),
                "updated_at" => now()->subDays(14),
            ],
            [
                "id" => 13,
                "user_id" => 5,
                "course_id" => 5,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(18),
                "updated_at" => now()->subDays(13),
            ],
            [
                "id" => 14,
                "user_id" => 9,
                "course_id" => 5,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(17),
                "updated_at" => now()->subDays(12),
            ],
            [
                "id" => 15,
                "user_id" => 14,
                "course_id" => 5,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(16),
                "updated_at" => now()->subDays(11),
            ],
            [
                "id" => 16,
                "user_id" => 20,
                "course_id" => 6,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(15),
                "updated_at" => now()->subDays(10),
            ],
            [
                "id" => 17,
                "user_id" => 25,
                "course_id" => 6,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(14),
                "updated_at" => now()->subDays(9),
            ],
            [
                "id" => 18,
                "user_id" => 30,
                "course_id" => 6,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(13),
                "updated_at" => now()->subDays(8),
            ],
            [
                "id" => 19,
                "user_id" => 16,
                "course_id" => 7,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(12),
                "updated_at" => now()->subDays(7),
            ],
            [
                "id" => 20,
                "user_id" => 21,
                "course_id" => 7,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(11),
                "updated_at" => now()->subDays(6),
            ],
            [
                "id" => 21,
                "user_id" => 26,
                "course_id" => 7,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(10),
                "updated_at" => now()->subDays(5),
            ],
            [
                "id" => 22,
                "user_id" => 17,
                "course_id" => 8,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(9),
                "updated_at" => now()->subDays(4),
            ],
            [
                "id" => 23,
                "user_id" => 22,
                "course_id" => 8,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(8),
                "updated_at" => now()->subDays(3),
            ],
            [
                "id" => 24,
                "user_id" => 27,
                "course_id" => 8,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(7),
                "updated_at" => now()->subDays(2),
            ],
            [
                "id" => 25,
                "user_id" => 18,
                "course_id" => 9,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(6),
                "updated_at" => now()->subDays(1),
            ],
            [
                "id" => 26,
                "user_id" => 23,
                "course_id" => 9,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(5),
                "updated_at" => now(),
            ],
            [
                "id" => 27,
                "user_id" => 28,
                "course_id" => 9,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(4),
                "updated_at" => now(),
            ],
            [
                "id" => 28,
                "user_id" => 19,
                "course_id" => 10,
                "certificate" => "ENTREGAT",
                "created_at" => now()->subDays(3),
                "updated_at" => now(),
            ],
            [
                "id" => 29,
                "user_id" => 24,
                "course_id" => 10,
                "certificate" => "PENDENT",
                "created_at" => now()->subDays(2),
                "updated_at" => now(),
            ],
            [
                "id" => 30,
                "user_id" => 29,
                "course_id" => 10,
                "certificate" => "LLIURAT",
                "created_at" => now()->subDays(1),
                "updated_at" => now(),
            ]
            ]
        );
    }
}
