<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("courses")->insert([
            [
                "id" => 1,
                "center_id" => 1,
                "name" => "Introducció a la Primeres Auxilis",
                "code" => "FA101",
                "hours" => 15,
                "type" => "Formació interna",
                "modality" => "presencial",
                "description" => "Aprèn les bases de les primeres auxilis, incloent RCP, cura de ferides i procediments d’emergència.",
                "is_active" => true,
                "assistant" => 1,
                "start_date" => now()->subDays(60),
                "end_date" => now()->subDays(55),
                "created_at" => now()->subDays(61),
                "updated_at" => now()->subDays(55),
            ],
            [
                "id" => 2,
                "center_id" => 2,
                "name" => "Seguretat al Treball",
                "code" => "SAF201",
                "hours" => 20,
                "type" => "Formació externa",
                "modality" => "online",
                "description" => "Coneix les normes de seguretat laboral i pràctiques per reduir riscos i prevenir accidents.",
                "is_active" => true,
                "assistant" => 2,
                "start_date" => now()->subDays(58),
                "end_date" => now()->subDays(53),
                "created_at" => now()->subDays(59),
                "updated_at" => now()->subDays(53),
            ],
            [
                "id" => 3,
                "center_id" => 3,
                "name" => "Primeres Auxilis Avançades",
                "code" => "FA201",
                "hours" => 25,
                "type" => "Formació interna",
                "modality" => "mixt",
                "description" => "Tècniques avançades de primeres auxilis, incloent avaluació del pacient i estabilització d’emergència.",
                "is_active" => true,
                "assistant" => 3,
                "start_date" => now()->subDays(56),
                "end_date" => now()->subDays(50),
                "created_at" => now()->subDays(57),
                "updated_at" => now()->subDays(50),
            ],
            [
                "id" => 4,
                "center_id" => 4,
                "name" => "Seguretat contra Incendis",
                "code" => "FS101",
                "hours" => 12,
                "type" => "Formació externa",
                "modality" => "presencial",
                "description" => "Aprèn la prevenció d’incendis, plans d’evacuació i com actuar amb seguretat davant un incendi.",
                "is_active" => true,
                "assistant" => 4,
                "start_date" => now()->subDays(54),
                "end_date" => now()->subDays(52),
                "created_at" => now()->subDays(55),
                "updated_at" => now()->subDays(52),
            ],
            [
                "id" => 5,
                "center_id" => 5,
                "name" => "Cura i Seguretat Infantil",
                "code" => "CCS101",
                "hours" => 18,
                "type" => "Formació interna",
                "modality" => "mixt",
                "description" => "Fonaments de la cura infantil, mesures de seguretat i preparació davant emergències per cuidadors.",
                "is_active" => true,
                "assistant" => 5,
                "start_date" => now()->subDays(52),
                "end_date" => now()->subDays(48),
                "created_at" => now()->subDays(53),
                "updated_at" => now()->subDays(48),
            ],
            [
                "id" => 6,
                "center_id" => 1,
                "name" => "Conscienciació en Salut Mental",
                "code" => "MH101",
                "hours" => 10,
                "type" => "Formació externa",
                "modality" => "online",
                "description" => "Aprèn a reconèixer problemes de salut mental i com donar suport bàsic a les persones afectades.",
                "is_active" => true,
                "assistant" => 1,
                "start_date" => now()->subDays(50),
                "end_date" => now()->subDays(48),
                "created_at" => now()->subDays(51),
                "updated_at" => now()->subDays(48),
            ],
            [
                "id" => 7,
                "center_id" => 2,
                "name" => "Ergonomia al Treball",
                "code" => "ERG101",
                "hours" => 8,
                "type" => "Formació interna",
                "modality" => "presencial",
                "description" => "Aprèn bones pràctiques d’ergonomia per prevenir lesions i millorar la productivitat.",
                "is_active" => true,
                "assistant" => 2,
                "start_date" => now()->subDays(48),
                "end_date" => now()->subDays(46),
                "created_at" => now()->subDays(49),
                "updated_at" => now()->subDays(46),
            ],
            [
                "id" => 8,
                "center_id" => 3,
                "name" => "Nutrició i Benestar",
                "code" => "NW101",
                "hours" => 15,
                "type" => "Formació externa",
                "modality" => "online",
                "description" => "Introducció a la nutrició, hàbits saludables i pràctiques de benestar general.",
                "is_active" => true,
                "assistant" => 3,
                "start_date" => now()->subDays(46),
                "end_date" => now()->subDays(43),
                "created_at" => now()->subDays(47),
                "updated_at" => now()->subDays(43),
            ],
            [
                "id" => 9,
                "center_id" => 4,
                "name" => "Habilitats de Comunicació",
                "code" => "CS101",
                "hours" => 20,
                "type" => "Formació interna",
                "modality" => "mixt",
                "description" => "Desenvolupa habilitats de comunicació efectives en l’àmbit personal i professional.",
                "is_active" => true,
                "assistant" => 4,
                "start_date" => now()->subDays(44),
                "end_date" => now()->subDays(40),
                "created_at" => now()->subDays(45),
                "updated_at" => now()->subDays(40),
            ],
            [
                "id" => 10,
                "center_id" => 5,
                "name" => "Estratègies de Treball en Equip",
                "code" => "TB101",
                "hours" => 12,
                "type" => "Formació externa",
                "modality" => "presencial",
                "description" => "Aprèn tècniques de treball en equip per millorar la col·laboració i la productivitat.",
                "is_active" => true,
                "assistant" => 5,
                "start_date" => now()->subDays(42),
                "end_date" => now()->subDays(39),
                "created_at" => now()->subDays(43),
                "updated_at" => now()->subDays(39),
            ]
    ]);
    }
}
