<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("projects")->insert([
            [
                "center" => 1,
                "name" => "project d'Inclusió Social",
                "start" => now()->subDays(30),
                "user" => 1,
                "description" => "Treball amb persones en risc d'exclusió social per millorar la seva qualitat de vida i autonomia.",
                "observations" => "Coordinar activitats, tallers i suport individualitzat per a la integració social.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(31),
                "updated_at" => now()->subDays(30),
            ],
            [
                "center" => 2,
                "name" => "Curs de Primeres Auxilis",
                "start" => now()->subDays(28),
                "user" => 2,
                "description" => "Formació en tècniques de reanimació, cura de ferides i actuació en situacions d'emergència.",
                "observations" => "Inclou pràctiques i simulacions per reforçar l'aprenentatge.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(29),
                "updated_at" => now()->subDays(28),
            ],
            [
                "center" => 3,
                "name" => "project de Medi Ambient",
                "start" => now()->subDays(26),
                "user" => 3,
                "description" => "Promoure pràctiques sostenibles i conscienciació ambiental a la comunitat.",
                "observations" => "Organitzar activitats de neteja, tallers educatius i campanyes de sensibilització.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(27),
                "updated_at" => now()->subDays(26),
            ],
            [
                "center" => 4,
                "name" => "Curs de Comunicació Eficaç",
                "start" => now()->subDays(24),
                "user" => 4,
                "description" => "Millorar habilitats comunicatives en entorns laborals i personals.",
                "observations" => "Inclou tècniques de comunicació verbal i no verbal.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(25),
                "updated_at" => now()->subDays(24),
            ],
            [
                "center" => 5,
                "name" => "project d'Activitats Culturals",
                "start" => now()->subDays(22),
                "user" => 5,
                "description" => "Organització d'activitats culturals per fomentar la participació i el gaudi artístic.",
                "observations" => "Inclou exposicions, concerts i tallers creatius.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(23),
                "updated_at" => now()->subDays(22),
            ],
            [
                "center" => 1,
                "name" => "Curs de Seguretat Laboral",
                "start" => now()->subDays(20),
                "user" => 10,
                "description" => "Formació sobre normativa i pràctiques segures en l'entorn laboral.",
                "observations" => "Inclou sessions teòriques i pràctiques.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(21),
                "updated_at" => now()->subDays(20),
            ],
            [
                "center" => 2,
                "name" => "project de Suport a Majors",
                "start" => now()->subDays(18),
                "user" => 6,
                "description" => "Programació d'activitats i serveis per a persones grans amb necessitats de suport.",
                "observations" => "Coordinació amb voluntaris i professionals del centre.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(19),
                "updated_at" => now()->subDays(18),
            ],
            [
                "center" => 3,
                "name" => "Curs de Gestió del Temps",
                "start" => now()->subDays(16),
                "user" => 7,
                "description" => "Tècniques i estratègies per organitzar millor les tasques i millorar la productivitat.",
                "observations" => "Inclou exercicis pràctics i plans personals de gestió del temps.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(17),
                "updated_at" => now()->subDays(16),
            ],
            [
                "center" => 4,
                "name" => "project d'Innovació Educativa",
                "start" => now()->subDays(14),
                "user" => 8,
                "description" => "Desenvolupament de projects per millorar processos i metodologies educatives.",
                "observations" => "Inclou activitats formatives per a docents i alumnes.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(15),
                "updated_at" => now()->subDays(14),
            ],
            [
                "center" => 5,
                "name" => "Curs de Benestar i Salut",
                "start" => now()->subDays(12),
                "user" => 9,
                "description" => "Coneixements bàsics sobre salut física i mental, alimentació i hàbits saludables.",
                "observations" => "Inclou xerrades i pràctiques guiades.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(13),
                "updated_at" => now()->subDays(12),
            ],
            [
                "center" => 1,
                "name" => "project d'Esports i Oci",
                "start" => now()->subDays(10),
                "user" => 15,
                "description" => "Organització d'activitats esportives i d'oci per a la comunitat.",
                "observations" => "Inclou tornejos, tallers i activitats recreatives.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(11),
                "updated_at" => now()->subDays(10),
            ],
            [
                "center" => 2,
                "name" => "Curs de Resolució de Conflictes",
                "start" => now()->subDays(8),
                "user" => 11,
                "description" => "Aprèn tècniques per gestionar i resoldre conflictes de manera efectiva.",
                "observations" => "Inclou simulacions i casos pràctics.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(9),
                "updated_at" => now()->subDays(8),
            ],
            [
                "center" => 3,
                "name" => "project de Tecnologia Social",
                "start" => now()->subDays(6),
                "user" => 12,
                "description" => "Aplicació de tecnologies per a millorar la qualitat de vida i serveis comunitaris.",
                "observations" => "Inclou desenvolupament de prototips i proves pilot.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(7),
                "updated_at" => now()->subDays(6),
            ],
            [
                "center" => 4,
                "name" => "Curs de Lideratge i Motivació",
                "start" => now()->subDays(4),
                "user" => 13,
                "description" => "Habilitats de lideratge i tècniques per motivar equips de treball.",
                "observations" => "Inclou activitats pràctiques i simulacions.",
                "is_active" => true,
                "type" => "commission",
                "created_at" => now()->subDays(5),
                "updated_at" => now()->subDays(4),
            ],
            [
                "center" => 5,
                "name" => "project de Voluntariat Comunitari",
                "start" => now()->subDays(2),
                "user" => 14,
                "description" => "Organització i coordinació d’activitats de voluntariat en diferents àmbits socials.",
                "observations" => "Inclou seguiment de participants i avaluació d'impacte.",
                "is_active" => true,
                "type" => "project",
                "created_at" => now()->subDays(3),
                "updated_at" => now()->subDays(2),
            ]
        ]);
    }
}
