<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("users")->insert([
            [
                "id" => 1,
                "name" => "Laura Fernández",
                "email" => "laura.fernandez@gmail.com",
                "phone" => "612345678",
                "role" => "professional",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123458",
                "locker_password" => "1234",
                "created_at" => now()->subDays(10),
            ],
            [
                "id" => 2,
                "name" => "Carlos Martínez",
                "email" => "carlos.martinez@gmail.com",
                "phone" => "623456789",
                "role" => "technical_team",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123457",
                "locker_password" => "1234",
                "created_at" => now()->subDays(8),
            ],
            [
                "id" => 3,
                "name" => "María López",
                "email" => "maria.lopez@gmail.com",
                "phone" => "634567890",
                "role" => "management_team",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123456",
                "locker_password" => "1234",
                "created_at" => now()->subDays(6),
            ],
            [
                "id" => 4,
                "name" => "Javier Ruiz",
                "email" => "javier.ruiz@gmail.com",
                "phone" => "645678901",
                "role" => "administration",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123455",
                "locker_password" => "1234",
                "created_at" => now()->subDays(4),
            ],
            [
                "id" => 5,
                "name" => "Ana Gómez",
                "email" => "ana.gomez@gmail.com",
                "phone" => "656789012",
                "role" => "professional",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123454",
                "locker_password" => "1234",
                "created_at" => now()->subDays(2),
            ],
            [
                "id" => 6,
                "name" => "Jana Torres",
                "email" => "jana.torres@gmail.com",
                "phone" => "667890123",
                "role" => "professional",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123453",
                "locker_password" => "1234",
                "created_at" => now()->subDay(),
            ],
            [
                "id" => 7,
                "name" => "Sergio Navarro",
                "email" => "sergio.navarro@gmail.com",
                "phone" => "678901234",
                "role" => "technical_team",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123452",
                "locker_password" => "1234",
                "created_at" => now()->subDays(12),
            ],
            [
                "id" => 8,
                "name" => "Paula Romero",
                "email" => "paula.romero@gmail.com",
                "phone" => "689012345",
                "role" => "administration",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123451",
                "locker_password" => "1234",
                "created_at" => now()->subDays(11),
            ],
            [
                "id" => 9,
                "name" => "David Alonso",
                "email" => "david.alonso@gmail.com",
                "phone" => "690123456",
                "role" => "management_team",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123450",
                "locker_password" => "1234",
                "created_at" => now()->subDays(9),
            ],
            [
                "id" => 10,
                "name" => "Lucía Ortega",
                "email" => "lucia.ortega@gmail.com",
                "phone" => "601234567",
                "role" => "professional",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123449",
                "locker_password" => "1234",
                "created_at" => now()->subDays(7),
            ],
            [
                "id" => 11,
                "name" => "Juan Carlos De la Cruz Gonzalez",
                "email" => "juancarlos.delacruz@gmail.com",
                "phone" => "602345678",
                "role" => "technical_team",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123448",
                "locker_password" => "1234",
                "created_at" => now()->subDays(5),
            ],
            [
                "id" => 12,
                "name" => "Natalia Ruiz",
                "email" => "natalia.ruiz@gmail.com",
                "phone" => "603456789",
                "role" => "management_team",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123447",
                "locker_password" => "1234",
                "created_at" => now()->subDays(4),
            ],
            [
                "id" => 13,
                "name" => "Andrés Pérez",
                "email" => "andres.perez@gmail.com",
                "phone" => "604567890",
                "role" => "administration",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123446",
                "locker_password" => "1234",
                "created_at" => now()->subDays(3),
            ],
            [
                "id" => 14,
                "name" => "Elena Castro",
                "email" => "elena.castro@gmail.com",
                "phone" => "605678901",
                "role" => "professional",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123445",
                "locker_password" => "1234",
                "created_at" => now()->subDays(2),
            ],
            [
                "id" => 15,
                "name" => "Rubén García",
                "email" => "ruben.garcia@gmail.com",
                "phone" => "606789012",
                "role" => "technical_team",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123444",
                "locker_password" => "1234",
                "created_at" => now()->subDay(),
            ],
            [
                "id" => 16,
                "name" => "Beatriz Molina",
                "email" => "beatriz.molina@gmail.com",
                "phone" => "607890123",
                "role" => "management_team",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123443",
                "locker_password" => "1234",
                "created_at" => now(),
            ],
            [
                "id" => 17,
                "name" => "Clara Vidal",
                "email" => "clara.vidal@gmail.com",
                "phone" => "608901234",
                "role" => "professional",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123442",
                "locker_password" => "1234",
                "created_at" => now()->subDays(13),
            ],
            [
                "id" => 18,
                "name" => "Raúl Ortega",
                "email" => "raul.ortega@gmail.com",
                "phone" => "609012345",
                "role" => "administration",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123441",
                "locker_password" => "1234",
                "created_at" => now()->subDays(12),
            ],
            [
                "id" => 19,
                "name" => "Patricia León",
                "email" => "patricia.leon@gmail.com",
                "phone" => "610123456",
                "role" => "management_team",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123440",
                "locker_password" => "1234",
                "created_at" => now()->subDays(11),
            ],
            [
                "id" => 20,
                "name" => "Iván Moreno",
                "email" => "ivan.moreno@gmail.com",
                "phone" => "611234567",
                "role" => "technical_team",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123439",
                "locker_password" => "1234",
                "created_at" => now()->subDays(10),
            ],
            [
                "id" => 21,
                "name" => "Cristina Ramos",
                "email" => "cristina.ramos@gmail.com",
                "phone" => "612345679",
                "role" => "professional",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123438",
                "locker_password" => "1234",
                "created_at" => now()->subDays(9),
            ],
            [
                "id" => 22,
                "name" => "Tomás Serrano",
                "email" => "tomas.serrano@gmail.com",
                "phone" => "613456780",
                "role" => "administration",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123437",
                "locker_password" => "1234",
                "created_at" => now()->subDays(8),
            ],
            [
                "id" => 23,
                "name" => "Lorena Pérez",
                "email" => "lorena.perez@gmail.com",
                "phone" => "614567891",
                "role" => "management_team",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123436",
                "locker_password" => "1234",
                "created_at" => now()->subDays(7),
            ],
            [
                "id" => 24,
                "name" => "Adrián López",
                "email" => "adrian.lopez@gmail.com",
                "phone" => "615678902",
                "role" => "technical_team",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123435",
                "locker_password" => "1234",
                "created_at" => now()->subDays(6),
            ],
            [
                "id" => 25,
                "name" => "Marta Sánchez",
                "email" => "marta.sanchez@gmail.com",
                "phone" => "616789013",
                "role" => "professional",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123434",
                "locker_password" => "1234",
                "created_at" => now()->subDays(5),
            ],
            [
                "id" => 26,
                "name" => "Pablo García",
                "email" => "pablo.garcia@gmail.com",
                "phone" => "617890124",
                "role" => "administration",
                "center" => "2",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123433",
                "locker_password" => "1234",
                "created_at" => now()->subDays(4),
            ],
            [
                "id" => 27,
                "name" => "Verónica Jiménez",
                "email" => "veronica.jimenez@gmail.com",
                "phone" => "618901235",
                "role" => "management_team",
                "center" => "3",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123432",
                "locker_password" => "1234",
                "created_at" => now()->subDays(3),
            ],
            [
                "id" => 28,
                "name" => "Hugo Fernández",
                "email" => "hugo.fernandez@gmail.com",
                "phone" => "619012346",
                "role" => "technical_team",
                "center" => "4",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123431",
                "locker_password" => "1234",
                "created_at" => now()->subDays(2),
            ],
            [
                "id" => 29,
                "name" => "Sara Blanco",
                "email" => "sara.blanco@gmail.com",
                "phone" => "620123457",
                "role" => "professional",
                "center" => "5",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123430",
                "locker_password" => "1234",
                "created_at" => now()->subDay(),
            ],
            [
                "id" => 30,
                "name" => "Diego Martín",
                "email" => "diego.martin@gmail.com",
                "phone" => "621234568",
                "role" => "management_team",
                "center" => "1",
                "status" => "active",
                "password" => Hash::make("123456"),
                "locker" => "T-123429",
                "locker_password" => "1234",
                "created_at" => now(),
            ]
        ]);
    }
}
